-- エンディングseedデータ
INSERT OR IGNORE INTO endings (ending_id, ending_layer, title_ja, title_en, description_ja, conditions_json, epilogue_ja, epilogue_en, priority) VALUES
('boss_clear', 'surface', 'ボス撃破', 'Boss Defeated', '最奥の敵を倒し、この世界の探索を終えた。', '{"requires_flag":"bishop_defeated"}', 'あなたは封印の司教を打ち倒した。しかし、何かが終わっていない気がする…', 'You defeated the Sealed Bishop. Yet something feels unfinished...', 10),
('flee_end', 'surface', '逃走', 'Fled', 'ボスから逃走した。', '{"requires_flag":"fled_from_boss"}', '背を向けて走った。恥ではない。生きていればまた来れる。', 'You turned and ran. No shame in that. You can always return.', 5),
('death_end', 'surface', '死亡', 'Death', 'HPが0になった。', '{"hp_zero":true}', 'あなたの意識は闇に沈む。だが、何かが残る…', 'Your consciousness fades to black. But something remains...', 1),
('residue_accept', 'hidden', 'Residue受容', 'Accept the Residue', 'ループの真実を知り、受け入れた。', '{"min_truth_stage":3,"requires_flags":["seal_truth_known","loop_aware"],"requires_choice":"accept_residue"}', '消し残りは消えない。あなたはそれを受け入れ、ループと共に在ることを選んだ。', 'Residue cannot be erased. You accept it, choosing to exist within the loop.', 50),
('residue_reject', 'hidden', 'ループ断ち切り', 'Break the Loop', 'ループの真実を知り、拒絶した。', '{"min_truth_stage":3,"requires_flags":["seal_truth_known","loop_aware"],"requires_choice":"reject_residue"}', 'あなたはループを断ち切る。代償は大きいが、前に進む道を選んだ。', 'You sever the loop. The cost is great, but you chose to move forward.', 50),
('crosslink_unity', 'hidden', '両世界統合', 'World Unity', '両世界のクロスリンクを完全に成立させた。', '{"requires_flags":["cross_quantum_delivered","cross_cipher_delivered","crosslink_all_complete"]}', '二つの世界が重なり、一つの真実が浮かび上がる。', 'Two worlds overlap, and a single truth emerges.', 60),
('true_end', 'true', '全痕跡回収', 'All Residue Collected', '全ての記憶フラグを回収し、真実に到達した。', '{"min_truth_stage":3,"requires_flags":["memory_n01","memory_n02","memory_n03","memory_n04","memory_n05","memory_n06","memory_n07","medieval_cleared","future_cleared"]}', 'すべての消し残りを辿り終えた。あなたは今、すべてを知っている。\nこのループに意味があったのか――その答えは、あなた自身が残痕として刻む。', 'You have traced every residue. Now you know everything.\nWhether this loop had meaning—that answer, you inscribe as your own residue.', 100);
